# Generated by Django 4.2.13 on 2026-05-25 11:07

import apps.audit.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=apps.audit.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ingestion_started', 'Ingestion started'), ('ingestion_completed', 'Ingestion completed'), ('ingestion_failed', 'Ingestion failed'), ('row_parse_failed', 'Row parse failed'), ('activity_created', 'Activity created'), ('activity_approved', 'Activity approved'), ('activity_flagged', 'Activity flagged'), ('activity_edited', 'Activity edited'), ('activity_locked', 'Activity locked'), ('bulk_approved', 'Bulk approval')], max_length=40)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
