# Generated by Django 4.2.13 on 2026-05-25 11:07

import apps.ingestion.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.UUIDField(default=apps.ingestion.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_mb51', 'SAP MB51 Flat File'), ('utility', 'Utility Portal CSV'), ('travel', 'Corporate Travel CSV')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('file_hash_sha256', models.CharField(blank=True, max_length=64)),
                ('row_count_total', models.IntegerField(default=0)),
                ('row_count_success', models.IntegerField(default=0)),
                ('row_count_failed', models.IntegerField(default=0)),
                ('row_count_flagged', models.IntegerField(default=0)),
                ('reporting_year', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingestion_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRow',
            fields=[
                ('id', models.UUIDField(default=apps.ingestion.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('failed', 'Failed')], default='ok', max_length=20)),
                ('parse_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_rows', to='ingestion.ingestionrun')),
            ],
            options={
                'db_table': 'raw_row',
            },
        ),
    ]
