# Generated by Django 4.2.13 on 2026-05-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawrow',
            options={'ordering': ['row_number']},
        ),
    ]
