# Generated by Django 4.2.13 on 2026-05-25 11:07

import apps.normalization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=apps.normalization.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('lpg', 'LPG / Propane'), ('natural_gas', 'Natural Gas'), ('heating_oil', 'Heating Oil'), ('electricity', 'Electricity'), ('flight_eco', 'Flight — Economy'), ('flight_bus', 'Flight — Business'), ('flight_first', 'Flight — First'), ('hotel', 'Hotel — per night'), ('car', 'Car — per km'), ('train', 'Train — per km')], max_length=30)),
                ('unit', models.CharField(max_length=20)),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(max_length=255)),
                ('valid_from_year', models.IntegerField()),
                ('valid_to_year', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'emission_factor',
            },
        ),
        migrations.CreateModel(
            name='NormalizedActivity',
            fields=[
                ('id', models.UUIDField(default=apps.normalization.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('diesel', 'Diesel'), ('lpg', 'LPG'), ('heating_oil', 'Heating Oil'), ('electricity', 'Electricity'), ('flight', 'Flight'), ('hotel', 'Hotel'), ('ground_transport', 'Ground Transport'), ('other', 'Other')], max_length=30)),
                ('activity_date', models.DateField()),
                ('period_end', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('facility_code', models.CharField(blank=True, max_length=50)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('cost_center', models.CharField(blank=True, max_length=50)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('scope', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=1)),
                ('scope3_category', models.IntegerField(blank=True, null=True)),
                ('original_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('original_unit', models.CharField(max_length=20)),
                ('original_currency', models.CharField(blank=True, max_length=3)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('normalized_kg_co2e', models.DecimalField(decimal_places=6, max_digits=18)),
                ('emission_factor_used', models.DecimalField(decimal_places=8, max_digits=18)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('is_flagged_suspicious', models.BooleanField(default=False)),
                ('flag_reasons', models.JSONField(default=list)),
                ('was_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('edit_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'normalized_activity',
                'ordering': ['-activity_date'],
            },
        ),
    ]
