# Generated by Django 4.2.13 on 2026-05-25 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('normalization', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedactivity',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalizedactivity',
            name='ingestion_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='ingestion.ingestionrun'),
        ),
        migrations.AddField(
            model_name='normalizedactivity',
            name='raw_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='activity', to='ingestion.rawrow'),
        ),
        migrations.AddField(
            model_name='normalizedactivity',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalizedactivity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['tenant', 'scope'], name='normalized__tenant__dcf13c_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['tenant', 'review_status'], name='normalized__tenant__0c9331_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['tenant', 'activity_date'], name='normalized__tenant__6cae44_idx'),
        ),
    ]
